### ISSUE TITLE
One hand mode

### ISSUE THREAD

**Issue by mad1mystic** [openboard-team/openboard#13]
It would be nice if we have one hand mode and adjustable height. Having swipe typing will make it perfect FOSS keyboard. The first release looks promising thank you for bringing FOSS keyboard Android doesn't have proper FOSS keyboard. Hope imp features are added in New releases

**Comment by jwsp1** [comment]
Swipe is already suggested in issue #3.
Adjustable height is already suggested in issue #8. So this issue can be closed as it's duplicate, or am I wrong?

**Comment by mad1mystic** [comment]
Yes those issues could be closed but would like Dev to notice about the app having obfuscated server pings calls to Google  . Would like to mention that the phone doesn't have any Google apps . May be AOSP libraries might be doing but just noticed that behavior. Thank you

**Comment by dslul** [comment]
I implemented a setting for custom keyboard height in 85b5b3c309485a06553fa9f0c991b3a692107f52. As @jwsp1 already said, many issues were duplicate except for one hand mode, so I guess we can keep this issue only for that (I'll change the title if you don't mind).

> Yes those issues could be closed but would like Dev to notice about the app having obfuscated server pings calls to Google . Would like to mention that the phone doesn't have any Google apps . May be AOSP libraries might be doing but just noticed that behavior. Thank you

Regarding this matter, I didn't have much time to investigate on this but yes, I think there are still some calls to google left (for dictionaries). I'll remove them as soon as possible, but we can continue the discussion [here](https://github.com/dslul/openboard/issues/10).

**Comment by MisterY** [comment]
This mode is very useful but usually only in combination with swipe typing. I find it very difficult to type on a one-hand-sized keyboard, but for swiping words, with a good dictionary and prediction, it is extremely useful.

**Comment by qw123wh** [comment]
the one-handed mode you can try to add by looking at this other Florisboard opensource keyboard. https://github.com/florisboard/florisboard
