### ISSUE TITLE
[BUG] Add input style icon almost invisible

### ISSUE THREAD

**Issue by AlexanderRitter02** [openboard-team/openboard#135]
## The bug

The "add" icon in `‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎‎‎‎‏‏‎‏‎‏‏‏‏‏‏‏‏‏‏‏‏‏‎‏‎‎‏‏‏‏‏‏‎‏‎‎‏‏‎‏‎‏‎‎‎‏‎‏‎‏‎‎‎‎‎‎‎‎‎‎‏‏‎‎‎‏‎‏‎‎‎‏‏‏‏‎‏‏‏‎‎‎‎Custom input styles` (to the right) is _too light_ to be visible.
The problematic file(s) is [ic_add_circle_white](https://raw.githubusercontent.com/dslul/openboard/master/app/src/main/res/drawable-hdpi/ic_add_circle_white_24dp.png).

![light_ico](https://user-images.githubusercontent.com/42546705/91068284-5e1f0300-e634-11ea-8476-a5bcb6c92bb7.jpg)

## Additional Details
- consider what happens when using dark mode
- I looked for a comparison how other apps do it, but wasn't able to find one
However I noticed it is common to do the plus in the bottom right as a circle:
<img src="https://user-images.githubusercontent.com/42546705/91071129-1b5f2a00-e638-11ea-88e5-86ee43e7ac9c.png" height="100" />
This might be a possible better way to do it.

**Comment by abn-volk** [comment]
This is because the app is using `Theme.DeviceDefault`, which varies from device to device. This can be fixed by using `Theme.Holo` on KitKat and `Theme.Material` on Lollipop and above (and choose variants with dark action bars such as `Light.DarkActionBar`)
