### ISSUE TITLE
"Always show number row" doesn't work for English (US) (Dvorak)

### ISSUE THREAD

**Issue by RefinedAnarchy** [openboard-team/openboard#244]
"Always show number row" doesn't work and switching to the numbers/symbols button on the very bottom left will result in a glitch that will not let the user switch back to the letters. I'm on GrapheneOS

**Comment by Phantom-Rehan** [comment]
Same problem here, but on QWERTY

**Comment by HolyR6S** [comment]
> "Always show number row" doesn't work and switching to the numbers/symbols button on the very bottom left will result in a glitch that will not let the user switch back to the letters. I'm on GrapheneOS

I have the exact same problem on android 10 (rooted S9+)
