### ISSUE TITLE
The language of the spell checker cannot be switched with the keyboard language

### ISSUE THREAD

**Issue by reaseno** [openboard-team/openboard#258]
The language of the spell checker (set to Open Board and System Language) cannot be switched with the keyboard language on Android 10. I tested this on two different devices.

Instead, the spell checker always uses the dictionary of the primary language (the language that is at the top) under System -> Languages & Input -> Languages.

That means, for example, if German is at the top, the spell checker only knows German, if English is at the top, only English. And as I said, this is independent of which language the keyboard itself is set to.

What does work, however, is suggesting words as you type in the selected language of the keyboard.

Now this means that if I have German set as my primary language and I set the keyboard to English and I type English, English words will be suggested to me, but everything I have typed will be underlined in red. If I tap on a word, only German suggestions are made to me.

How can I change this without disabling the spell checker completely?

**Comment by Inrumpo** [comment]
I have the same or a similar issue. I'm using OpenBoard 1.4.3 on a CalyxOS 2.8.0 Pixel phone.
I've set OpenBord as my keyboard and as my spell checker and I've chosen two languages (English and German). Suggesting words does work (German showing German words / English showing words in English).
Spell checking isn't working though: Spell checking will always be in English. Therefore everything will be marked as wrong (underlined in red) when writing in German.

**Comment by ristein** [comment]
@Inrumpo are you sure the red underlining spell check is not by android itself?

**Comment by reaseno** [comment]
@ristein if thats so, than OpenBoard should disable it or switch the language. It is possible, as the Google keyboard shows.

**Comment by Inrumpo** [comment]
> @Inrumpo are you sure the red underlining spell check is not by android itself?

I've set "OpenBoard Spell Checker" as my spell checker in the system settings.
"Use system languages" is set for languages while the ones chosen are English (UK) and German (CH).

**Comment by ClearlyClaire** [comment]
I have the same issue. Looking at the code, it seems that the spellchecker component of OpenBoard uses a dictionary based on the result of `getLocale`, so it makes sense that it only spellchecks for the system locale.

However, I'm pretty sure LineageOS 16 and below didn't have this issue, but I couldn't find anything in the code that suggested they were doing it differently (I might have missed it, though)

**Comment by jnnkB** [comment]
This issue was fixed with #526. Make sure you've enable the OpenBoard Spell Checker in the Android settings if you want to try this out.

**Comment by ClearlyClaire** [comment]
I can confirm this works fine, thanks!
