### ISSUE TITLE
I want copy tool and emoji support

### ISSUE THREAD

**Issue by imrohitkumar** [openboard-team/openboard#301]
I want cut paste support and emoji support like in this keyboard.
https://github.com/florisboard/florisboard

**Comment by NSTAdventure** [comment]
> I want cut paste support and emoji support like in this keyboard.
> https://github.com/florisboard/florisboard

Agree!

Anyway florisboard still in alpha stage right?

**Comment by imrohitkumar** [comment]
Yes, but they have good design, So i think some features should be imported to openboard.

**Comment by jnnkB** [comment]
Isn't emoji support fixed in https://github.com/dslul/openboard/pull/242?

**Comment by MajeurAndroid** [comment]
Fixed in #242 and #483.
