### ISSUE TITLE
Emoji row with AMOLED black theme turns white

### ISSUE THREAD

**Issue by OLoKo64** [openboard-team/openboard#376]
**Describe the bug**
When using the AMOLED dark mode theme the row to select emojis becomes white, making very hard to see.

**To Reproduce**
1. Select AMOLED Black Dark Theme.
2. Open the emoji selector.
3. The row that selects the type of emojis becomes white

**Expected behavior**
This should have a black background as the rest of the other menus

**Screenshots**
[https://i.imgur.com/iW8RgTL.png](https://i.imgur.com/iW8RgTL.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Android 11

**Comment by dslul** [comment]
Are you referring to Material Dark (AMOLED)? On Android 10 and 7 I couldn't reproduce this issue


![image](https://user-images.githubusercontent.com/6121202/120071155-390d6400-c08e-11eb-9b3b-2252c99340ed.png)

**Comment by OLoKo64** [comment]
> Are you referring to Material Dark (AMOLED)? On Android 10 and 7 I couldn't reproduce this issue
> 

Exactly the Material Dark (AMOLED) on my device become white. 
As this is a common issue when Force Dark Mode is enabled, but mine isn't, I reported.

When using the Material Dark without AMOLED everything is fine, and the bar is dark like in your pic.

[Another picture](https://i.imgur.com/1lH4dzk.png) of the bug on another app.

**Comment by Oymate** [comment]
@OLoKo64  you can use github's native image upload :)

**Comment by xXSofyanXx** [comment]
thanks a lot man!! fixed my problem
