### ISSUE TITLE
Toggling Number row ON is not working on tablets

### ISSUE THREAD

**Issue by RHJihan** [openboard-team/openboard#406]
Toggling `Number row` ON is not working on tablets. 
(The dedicated Emoji key is not also behaving the same. But I am unsure about the emoji key, as there is a persistent emoji button on the keyboard for tablets.)

**Steps to reproduce**
1. Go to _OpenBoard settings_
2. Toggle `Number row` ON form _Preferences_ (also `Show emoji key`)
3. Check keyboard on any text field

**Behaviour**
There should be a dedicated row for numbers on the keyboard, but there would not.

**Emulator**
Name: 13.5_Freeform_API_30
Android version: 11.0
API level: 30
Resolution: 2560 × 1440 hdpi

**Comment by Sudrien** [comment]
Same for me, 1.4.3 off Fdroid

**Comment by Sudrien** [comment]
#273 a dupe

**Comment by Sudrien** [comment]
#244 a dupe

**Comment by user8446** [comment]
No number row for me as well on an ASUS tablet on Android 7. However, on my Android 10 phone it works as expected.

This might me related to https://github.com/openboard-team/openboard/issues/498
