### ISSUE TITLE
Appearance & Layout THEME

### ISSUE THREAD

**Issue by Dlonraz** [openboard-team/openboard#490]
Could you add to THEMES...

> ### **HOLO YELLOW** to Material Dark Border

> ### **HOLO BLUE** to Material Light Border

Thank you.

**Comment by MajeurAndroid** [comment]
Can you be more specific ?

**Comment by Dlonraz** [comment]
Openboard Settings >> Appearance & Layouts >> Theme 

In the THEME settings you offer 10 theme settings which include amongst others...

- Material Light Border
- Material Dark Border
- Holo White
- Holo Blue

Could you config the Material Dark Border with the Holo Blue colour accents, but instead of using blue accents rather use yellow accents on the Material Dark Border and blue accents on the Material Light Border.

If you are able to do this, it will make the Material Dark Border and Material Light Border options much more user appealing.

Thank you for the prompt response.

**Comment by MajeurAndroid** [comment]
You can find documentation online on android Themes and try to extend one of the existings.
For now, new themes are not planned I guess.

**Comment by Dlonraz** [comment]
Noted with appreciation.
