### ISSUE TITLE
German capital eszett

### ISSUE THREAD

**Issue by UserX404** [openboard-team/openboard#495]
In the german layout the capital Eszett letter is missing.
It's not that big issue due to it's rarely used but for integrity it should be added.

![screenshot](https://i.imgur.com/t0ISn51.jpg)

Additional info: [Wikipedia](https://en.wikipedia.org/wiki/%C3%9F#Development_of_a_capital_form)
U+1E9E ẞ LATIN CAPITAL LETTER SHARP S
It's part of unicode since 2007.

**Comment by jnnkB** [comment]
There already is an open pull requests which I think implements what you want: #431

**Comment by UserX404** [comment]
I only searched issues for dupes and not PRs.
Thank you for linking!

**Comment by UserX404** [comment]
Yeah, issue is back again in 1.4.5

**Comment by MajeurAndroid** [comment]
Same answer than #657, I'll fix this soon.
