### ISSUE TITLE
Allow disabling clipboard history

### ISSUE THREAD

**Issue by Etim-Orb** [openboard-team/openboard#497]
I have modified this question to an issue since it seems there is no issue for this feature for this feature being implemented yet.

**Comment by dasaferi** [comment]
also I would like a button to disable the new clipboard function, I don't like having the history saved for privacy.

**Comment by Etim-Orb** [comment]
@MajeurAndroid Was this implemented? When will the next release get released?

**Comment by MajeurAndroid** [comment]
Yes it is now an option, it will be in the next release, I cannot give you a date unfortunately, @dslul takes care of releases.
