### ISSUE TITLE
No number row

### ISSUE THREAD

**Issue by cordelia04m** [openboard-team/openboard#498]
App version: 1.4.4

Android version: 10

On the previous version, there is a number row on the top, while on 1.4.4 the row is gone. I have the "number row" choice in the setting select but this doesn't add the number row back.

**Comment by entrapta-dev** [comment]
Similarly, the Language button setting also has no effect. Keyboard never shows number row or language button regardless of setting.

Edit: Emoji button setting is also ignored.

**Comment by dslul** [comment]
Strange, I'm also on 10 and all the things you mentioned work on my device. Let's see if someone else can reproduce this issue.

**Comment by entrapta-dev** [comment]
I can't explain it, as I had switched between apps and whatnot many times with the issue persisting, but now it's suddenly all back to how it's supposed to be.

**Comment by chrismacr** [comment]
I can confirm on version 1.4.4 and Android 11 no number row shows up with the setting turned on.

**Comment by JM480** [comment]
My tablet running Android 10 has had this issue before this update and it still has this issue with version 1.4.4.

**Comment by cordelia04m** [comment]
@entrapta-dev 
That's strange. The number row is back for me as well, I didn't do anything. Seems like it's an android bug bug or something but not OpenBoard's bug.

**Comment by JM480** [comment]
> @entrapta-dev That's strange. The number row is back for me as well, I didn't do anything. Seems like it's an android bug bug or something but not OpenBoard's bug.

I don't have this issue with Simple Keyboard on my tablet so it's probably an issue with OpenBoard.

**Comment by RevanProdigalKnight** [comment]
It appears this issue occurs when using a custom layout for me (Dvorak, etc.), and only when viewing that particular layout (Android 12, v1.4.4). As soon as I change to the numbers and symbols layout(s) I have a separate numbers row again.
