### ISSUE TITLE
French layout

### ISSUE THREAD

**Issue by trev0r-STA** [openboard-team/openboard#516]
For the euro countries, you should display the € symbol instead of the $ symbol on the d touch
Layout which are wrong:
French
Finnish
Spanish
Luxembourgish
Italian
Portuguese

Maybe could I make the job. Just say to me where are the layout's.

Thanks

**Comment by Garettman** [comment]
I solved it ! You need to change the following code in `app/src/main/res/xml/rowkeys_azerty2.xml ` in order to change the currency sign:
Maybe there is another way without changing all azerty layouts, but I haven't investigated this.
`
    <Key
        latin:keySpec="d"
        latin:keyHintLabel="$"
        latin:additionalMoreKeys="$"
        latin:moreKeys="!text/morekeys_d" />
`
to

`
    <Key
        latin:keySpec="d"
        latin:keyHintLabel="€"
        latin:additionalMoreKeys="€"
        latin:moreKeys="!text/morekeys_d" />
`

Tu es français ?

**Comment by Garettman** [comment]
It's not a good solution tho.
We'll have to create specific files if I'm right.
I'll work on it when I got time

**Comment by trev0r-STA** [comment]
I've submit a [PR](https://github.com/openboard-team/openboard/pull/519) with the correction
But apparently, there is another problem. It does not come from here

Et sinon, oui, je suis français :smile:

**Comment by trev0r-STA** [comment]
I don't understand a lot :rofl: 
Modify some text files is ok for me. But dive into the Java code, not for me

Tkt, je ne comprends rien non plus :rofl: 
Modifier des fichiers textes, ok. Plonger dans le code... Très peu pour moi, surtout Java

**Comment by Garettman** [comment]
Je regarderais ça demain, mais c'est sans garantie de réussite 🤣  vive l'open source en tout cas

**Comment by MajeurAndroid** [comment]
I'll try to review the PR this weekend. For me, the french keyboard correctly displays the euro symbol 🤔

**Comment by MajeurAndroid** [comment]
See https://github.com/openboard-team/openboard/pull/519#issuecomment-1030872884, this should be fixed in next release.
