### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by 15bart15** [openboard-team/openboard#517]
Hello
There is a lot of settings which are not translate in French
![Screenshot_2022-01-31_12-21-19](https://user-images.githubusercontent.com/17881601/151785374-42b6a4f3-827b-4f3d-8581-1e63b7975d69.png)

How can I help ? I don't find a transiflex, nor something like that to translate. Where are translations stored ?

Thanks

**Comment by MajeurAndroid** [comment]
We are still waiting for approval on weblate for now, it should be ready in few days.

**Comment by MajeurAndroid** [comment]
@trev0r-STA translation is now ready on weblate, you can translate missing strings to french. Don't forget to try to stick as much as possible to the existing sentence formats and wordings. Thanks

**Comment by trev0r-STA** [comment]
@MajeurAndroid 
Translation OK.
