### ISSUE TITLE
Amoled theme with borders + one hand mode 

### ISSUE THREAD

**Issue by SosPosos** [openboard-team/openboard#523]
Please make an amoled theme with borders like one in the GBoard, i just can't use one without the borders
Photo:
https://ibb.co/DGXbkJ9
dark mode OpenBoard theme looks not as good as this theme in GBoard.
and i really need one hand mode - with large phone it feels so bad to use keyboard without one hand mode

**Comment by MajeurAndroid** [comment]
Dark theme with border already provides what you want. For one-handed mode, a PR is comming.
