### ISSUE TITLE
Give hints when voice input is not available

### ISSUE THREAD

**Issue by genodeftest** [openboard-team/openboard#541]
**Is your feature request related to a problem? Please describe.**
After installing OpenBoard, I chose to configure it including enabling _OpenBoard Settings_ → _Preferences_ → _Voice input key_. When typing, a microphone symbol is displayed, but clicking on it does nothing.
This seems to be related to the fact that I don't have a voice input software installed.

**Describe the solution you'd like**
When enabling _Voice input key_ without having any voice input software installed/configured, OpenBoard should show a hint, explaining this to the user.
When clicking on the microphone symbol in the keyboard's top row without having any voice input software installed/configured, OpenBoard should show a hint too.
Ideally, the hint should explain how to enable or install a voice input software. Since it seems to be hard to install such software (I couldn't find a guide to install FOSS STT software), I guess it would be ok for now to just display the hint that no voice input software has been found and thus the feature won't work, disabling it again.

**Describe alternatives you've considered**
No workaround found because I cannot find a "voice input" software which can be configured as such in Android's system settings

**Additional context**
I'm using OpenBoard 1.4.4b from F-Droid on Android 11 with most google apps disabled, including _Google App_ and _Google Assistant_

**Comment by Helium314** [comment]
The related code and the message actually exist, but apparently there is a bug when detecting whether there is no voice input.
