### ISSUE TITLE
The space between buttons lines is slightly long

### ISSUE THREAD

**Issue by kareeeeeeeem** [openboard-team/openboard#549]
**Describe the bug**
The space between the buttons lines looks long, and takes space on screen.
Others keyboards don't seem to have this much of space

**To Reproduce**
1. Just open the keyboard and compare it to gboard or Florisboard

**Screenshots**
Openboard and florisboard
![Screenshot_20220224-105504](https://user-images.githubusercontent.com/52888633/155502770-0488f26f-8fd3-46d0-b105-5cff0df409bf.png)
![Screenshot_20220224-105511](https://user-images.githubusercontent.com/52888633/155502783-1e4b9b6c-ba21-4513-9955-f65c8384f58b.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S9]
 - OS: [e.g. Android 10]

**Additional context**
Also chaging the keyboard height settings looks to shrink the buttons high not the actual space between them

**Comment by MajeurAndroid** [comment]
@kareeeeeeeem hitboxes of keys do not depend on the background you see behind a key. In terms of behaviour, only the visual style changes between the two keyboards you mentionned and Openboard.
