### ISSUE TITLE
Add an anti-biometric fingerprinting option against keypress timing analysis

### ISSUE THREAD

**Issue by Skavard** [openboard-team/openboard#550]
Many big tech companies uses many techniques to collect our data even if we try to be anonymous. Even if we use many front-end programs to anonymize ourselves, they could just analyze the timing of our keypress to fingerprint us. Facebook already collects the data on how long the user scrolls through the feeds so this technique already exists beyond just theoretical.

One way to help mitigate this is by adding an option that makes the keypress timing similar across users by delaying the sending of the keystroke even by just a few milliseconds and averaging them all out so that the service on the other end will have a harder time differentiating one person from the crowd.

**Comment by MajeurAndroid** [comment]
@Skavard I don't think any other app is able to monitor keypresses of our keyboard. Each app has its own window and input logic, entirely "sandboxed". The only way that could happend would be through an over-the-screen service, that needs to be explicitly authorized by the user.

**Comment by Skavard** [comment]
@MajeurAndroid I'm referring to the app at the other end being able to collect the data on the time it takes to receive the individual keystrokes making it vulnerable to analysis of the timing patterns an individual subconsciously makes and deanonymize them making this a privacy vulnerability that can be addressed by adding an option to delay the keystrokes and make them uniform across all users. Maybe even make the option the default so that out of the box all users look the same in their keypress timing.
