### ISSUE TITLE
Add haptic feedback while typing

### ISSUE THREAD

**Issue by jsoberg** [openboard-team/openboard#571]
**Is your feature request related to a problem? Please describe.**
There is no haptic feedback for key presses with OpenBoard.

**Describe the solution you'd like**
Using Gboard on my Pixel 6, each keypress has a small vibration which provides great user feedback while typing. If possible, I suggest that we add the option for similar haptic feedback so that each keypress results in a small vibration.

**Additional context**
I'm using the current version of OpenBoard on Google Play (1.4.4b) on a Pixel 6 running Android 12.

**Comment by Helium314** [comment]
Does it work when enabling "vibrate on keypress" in OpenBoard preferences?

**Comment by jsoberg** [comment]
Thanks, it does! I wasn't aware of the preferences before.

Should this be enabled by default? I think haptic feedback is on by default with most keyboards but I'm not 100% sure.

**Comment by Helium314** [comment]
It used to be enabled by default, but was changed a while ago in https://github.com/openboard-team/openboard/commit/cd14d5630b966e7fda42928e8d2da18ea78cb174.

Default value could be changed to use system setting for `Settings.System.HAPTIC_FEEDBACK_ENABLED`, but that's a bit too much work for such a (in my opinion) minor issue.
