### ISSUE TITLE
number row issues

### ISSUE THREAD

**Issue by boobas2** [openboard-team/openboard#572]
When "always show number row" option is enabled:

1. Number row doesn't show.
2. When switched to symbols layer via ?123 key, it will not switch back to the letters layer via said key - the keyboard will just flicker and stay on symbols layer. Works as expected with number row disabled.

Openboard 1.4.4b
Stock Android 11
Fairphone 4

**Comment by qw123wh** [comment]
@boobas2 this problem has already been solved, you just have to wait for the app update to be released
