### ISSUE TITLE
I saw that the ability to disable clipboard history has been merged. Qhere can I go to disable clipboard history?

### ISSUE THREAD

**Issue by pinckpockett** [openboard-team/openboard#582]
**Describe the bug**
I cannot seem to find the setting to disable clipboard history.

I am on the latest version of openboard. After looking through the issues, I saw a few issues ooen on the matter. On February the feature was merged. I have beem looking in setttings but can't seem to find it.  Where do I go to disable clipboard history. It is not the most privacy minded feature.

**Comment by MajeurAndroid** [comment]
There has been no release since that merge, we'll need to wait for a release.

**Comment by gbdomubpkm** [comment]
Hello. I just realized this problem and it's really against privacy, not to mention the risk of making a mistake in pasting. When will the next update be? This problem absolutely needs to be fixed!

**Comment by MajeurAndroid** [comment]
In the upcoming days, I guess.
