### ISSUE TITLE
Text Correction aka Auto Correct issues for email address

### ISSUE THREAD

**Issue by AntaeusBastiat** [openboard-team/openboard#589]
Anytime I type an email address such as "[email@address.com](mailto:email@address.com)", the text correction function will correct it as "email address com". I have tried adding every variation of "@address.com" to the personal dictionary, with no luck. Unless you add the exact email address to the personal dictionary, then it will auto correct it. Is there a setting I am missing or something I am doing incorrectly, because this seems kind of strange.

**Comment by jnnkB** [comment]
Duplicate of #425
