### ISSUE TITLE
Space bar trackpad support in RTL languages

### ISSUE THREAD

**Issue by IamHaddad** [openboard-team/openboard#598]
**Describe the bug**
The space bar trackpad does not support RTL languages

**To Reproduce**

1. Enable space bar trackpad 
2. Add an RTL language like Persian or Arabic
3. Use space track to change pointer location

**Expected behavior**

By dragging to the right, it's supposed to go right, but it's going to the left instead

**Smartphone (please complete the following information):**
 - Device: Poco F3
 - OS: MIUI 13 (android 12)

**Comment by MajeurAndroid** [comment]
This has been fixed in #570
