### ISSUE TITLE
Clipboard Key Doesn't Copy When Pressed

### ISSUE THREAD

**Issue by adarsh1001** [openboard-team/openboard#601]
**Describe the bug**
As per the info in settings, the clipboard key is supposed to copy when pressed and paste when long pressed. However, pressing it opens the clipboard history instead of copying the text. Long press to paste is working fine.

**To Reproduce**
1. Go to Openboard Settings -> Preferences.
2. Enable the Clipboard Key.
3. Summon the keyboard on a text field, write some text and press the clipboard key.
4. Clipboard history gets opened.

**Expected behavior**
It should copy the text as stated in the settings.

**Smartphone (please complete the following information):**
 - Device: LG Wing
 - OS: Android 11

**Comment by Anonymous2716** [comment]
Well that is the behavior. It doesn't copy .you have to copy manually as you would normally. On long press on the clipboard button will past the last copied text.  As I understand it from my few months of experience.

**Comment by Helium314** [comment]
> As per the info in settings, the clipboard key is supposed to copy when pressed and paste when long pressed

Where in the settings does it say that? The "Clipboard key" setting doesn't have any description.

**Comment by adarsh1001** [comment]
@Helium314 It had a description in the previous release (v1.4.4b) back when the issue was raised.

![Screenshot_2022-08-21-21-51-44-403.jpeg](https://user-images.githubusercontent.com/8820038/185801511-53f480d3-357f-45fb-8ae7-acf2862f4321.jpeg)

Looks like it was removed in the current release. If going forward, the idea is to not use the clipboard key in the aforementioned fashion then we can close the issue.

**Comment by Helium314** [comment]
Thanks! The description was removed in https://github.com/openboard-team/openboard/commit/5b332fca2e800a5409ccde430a4f7ffa211e71b3

@MajeurAndroid I guess like it was removed because the description isn't correct (any more), right?

**Comment by MajeurAndroid** [comment]
@Helium314 you're right. It was removed when clipboard history has been implemented. 
The current behaviour is what is expected

**Comment by adarsh1001** [comment]
Thanks folks, closing the issue then.
