### ISSUE TITLE
Keyboard height scale not working

### ISSUE THREAD

**Issue by ThHareau** [openboard-team/openboard#604]
**Describe the bug**
Keyboard height scale not working, the scale stays at the default value

**To Reproduce**
1. Go to Settings / Appearence and layout 
2. Enable keyboard resizing
3. Select 125 as a scale (or any other scale)
4. Open the keyboard, compare with before, the scale did not change

**Expected behavior**
The height scale changes the keyboard scale

**Screenshots**

| ![image](https://user-images.githubusercontent.com/9265111/167689513-ab23e2f5-0621-40f6-8527-dda91077c4dc.png)        | ![image](https://user-images.githubusercontent.com/9265111/167689543-8cb45c41-1207-4c96-8fb2-9149c2b7455b.png)        |
|--------------|--------------|
| height: 100% | height: 125% |

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 12

**Additional context**

On version 1.4.3 it's working fine. On version 1.4.2 it's not working. 

I tried running the emulator, I could not reproduce :/

**Comment by MajeurAndroid** [comment]
Can you reproduce this in 1.4.4 ?

**Comment by ThHareau** [comment]
I'll try and keep you posted :)

**Comment by ThHareau** [comment]
Yes, I do reproduce on 1.4.4b.

**Comment by ThHareau** [comment]
Hi, it seems to have been fixed in the 1.5 version. I'll close the issue
