### ISSUE TITLE
Add new emoji?

### ISSUE THREAD

**Issue by iamarkadyt** [openboard-team/openboard#614]
Is it possible to add this emoji into the keyboard emoji set?
![image](https://user-images.githubusercontent.com/23281304/170319886-7dde020c-42ba-4d76-84e9-b3867fae3984.png)
Actual character: 🥹 (may look different on MacOS)

Alternatively, is there a way to modify the emoji set manually as a user, and not the application developer?

**Comment by Tsangares** [comment]
🥺 
Using open board right now

**Comment by Tsangares** [comment]
🥺 plz

**Comment by MajeurAndroid** [comment]
It is already here ! See app/src/main/res/values/emoji-categories.xml#L61.
Two reasons you don't see it:
- Your phone is running an older android version than 32 (don't remember the commercial name)
- You have an older version of openboard

**Comment by iamarkadyt** [comment]
@MajeurAndroid it seems that you're right, I am using a version released before this commit [commit](https://github.com/openboard-team/openboard/commit/9f66d614541cc4384dcea47261092a2d561c9e4f), but the problem is there hasn't been a release that includes it yet!

Latest release, 1.4.4b is about 10 commits back. Is there a way to manually build the APK file or maybe somehow help prepare a new release? I'd be down to help!
