### ISSUE TITLE
Double Tap

### ISSUE THREAD

**Issue by chandrab699** [openboard-team/openboard#617]
**Is your feature request related to a problem? Please describe.**
Double tap on keys. Is it possible to implement double tap gesture on keys.
Same double tap on "a", in Qwerty keyboard to get "A" as output.

**Describe the solution you'd like**
Double tap gesture needed in the keys

**Comment by NoahAndrews** [comment]
What if you need to type something like "llama" or "aardvark" or "oops"? That would be an extremely frustrating experience, especially if it also applied to the many words with double letters in the middle of them, like "pool".

**Comment by MajeurAndroid** [comment]
@NoahAndrews says it all, unfortunately it's not something we can do.
