### ISSUE TITLE
When is the new release coming?

### ISSUE THREAD

**Issue by iamarkadyt** [openboard-team/openboard#619]
It looks like there hasn't been a release in about 4 months. There are some features that have been added since then, like new emojis that are impossible to get to unless you build a dev APK and install it yourself.

Wondering if I could help with a new release? Or just what the plans are. Thanks!

**Comment by MayuraVerma** [comment]
1. Double Tap gesture on letter keys
2. TransliterationMethod

Would be great features

**Comment by brnwlshubh** [comment]
@iamarkadyt By the time use apk for the latest update from action section

**Comment by Pentaphon** [comment]
I do find it odd that the "Openboard Team" hasn't been seen since May. There seems to be only 2 people on the "team" as well. 

Perhaps they should find a 3rd member that could help them when they aren't around.

**Comment by MajeurAndroid** [comment]
AOSP keyboard, and by extension OpenBoard is a very technical and difficult project. Each contribution takes a lot of time to be figured out. It is also one of the reasons why new contributors aren't that frequent.
Please avoid asking for 'new contributors/maintainers' or more time spent on the project by contributors, as **both of these things are out of our control**. We obviously would love to have more time and more contributors to make Openboard next level, but unfortunately, there is external constraints to take into account.
We cannot give ETA as every contributor do this on its free-time, that he may not have, which I assume is the case for @dslul and I since several months.

**Comment by MajeurAndroid** [comment]
@shivknight @Pentaphon @Anonymous2716 @Offerel @urmomsangus @iamarkadyt @MayuraVerma @brnwlshubh The long-awaited release is finally here. See [v1.4.5](https://github.com/openboard-team/openboard/releases/tag/v1.4.5).

**Comment by Anonymous2716** [comment]
@MajeurAndroid  wow lots of new works I see. Checked the repo this morning . thanks.

**Comment by Anonymous2716** [comment]
![1](https://user-images.githubusercontent.com/78570872/183226097-a05993a6-7647-4762-8aa2-ddc81bb85683.png)


@MajeurAndroid not available on fdroid yet . so out of curiosity I built it on my android phone. There's is the keyboard itself and the build info. Did just for fun . waiting for fdroid repo to update it. It works pretty well.

**Comment by Pentaphon** [comment]
> @MajeurAndroid not available on fdroid yet

fdroid usually takes 3 days or so. It's not on the Play Store yet either because that can be staggered. We just have to wait.

**Comment by Anonymous2716** [comment]
@Pentaphon that's okay previous version works well tho.

**Comment by MayuraVerma** [comment]
> @shivknight @Pentaphon @Anonymous2716 @Offerel @urmomsangus @iamarkadyt @MayuraVerma @brnwlshubh The long-awaited release is finally here. See [v1.4.5](https://github.com/openboard-team/openboard/releases/tag/v1.4.5).

Does it support double tap gesture on letters?

**Comment by Pentaphon** [comment]
@MajeurAndroid still no release on Google Play. Was this release staggered to come out only to some devices at a time?

fdroid is slow as usual but that is expected.

**Comment by MajeurAndroid** [comment]
@Pentaphon this will be F-Droid only, Playstore is not managed by the 'openboard team' but by @dslul himself as it is its personal store account.

**Comment by Anonymous2716** [comment]
@Infinitytreacher  checkout these posts. I said it there and you might have to do some tweak on your own.

https://www.reddit.com/r/termux/comments/wiobz5/build_apps_on_termux_with_and_without_gradle_its/

https://www.reddit.com/r/termux/comments/wzs8nt/documentation_of_building_android_apps_in_termux/
