### ISSUE TITLE
Autofill compatibility

### ISSUE THREAD

**Issue by pm09sx** [openboard-team/openboard#622]
Hello,

I truly love this keyboard, but one functionality it lacks is the compatibility with inline autofill services (like bitwarden)

I'd live to know if you think it could be possible
Thanks !

**Comment by pm09sx** [comment]
#387 was left unanswerd a long time ago

**Comment by MajeurAndroid** [comment]
I think we should have a list of the most wanted features so we can prioritize them. Auto fill is clearly more reachable than glide typing.
