### ISSUE TITLE
*insert here language name* language

### ISSUE THREAD

**Issue by boxsuny** [openboard-team/openboard#624]
Hello, developer, I finished the translation of Chinese language in weblate, but in the app language selection, I still can't use Chinese (ps: not a programmer, not very clear about this information), I hope you can help me answer my doubts。
![图片](https://user-images.githubusercontent.com/99521660/174228598-e0286cd4-e987-439d-bf2b-43d547de627d.png)

**Comment by MajeurAndroid** [comment]
Thanks for your contribution, translations are added in the app at each release. Your contributions will be available in next release.
