### ISSUE TITLE
How to show IOS emoji?

### ISSUE THREAD

**Issue by shahzad1** [openboard-team/openboard#629]
Is there any way to show IOS emoji list rather than the default Android emoji?

**Comment by AzzyC** [comment]
This is not a keyboard bug. Your system must contain the iOS emoji font style to show iOS emoji's. This can only be done on a device with root access to be able to swap the default emoji font file with iOS style emoji font file

**Comment by MajeurAndroid** [comment]
@AzzyC is right.
