### ISSUE TITLE
missing Keycap emojis

### ISSUE THREAD

**Issue by Sosasees** [openboard-team/openboard#648]
**Is your feature request related to a problem? Please describe.**

after i switched from system keyboard to OpenBoard, i eventually wanted to use these emojis, but i noticed they were missing from the emojis list:
#️⃣*️⃣0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣

i was disappointed that i had to copy-paste them from a webpage

the 🔟 emoji is in the list, so it's even stranger that the rest isn't here

**Describe the solution you'd like**

please add these emojis to the emojis list, just before 🔟:
#️⃣*️⃣0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣

i wanted to do this myself but i couldn't find the emojis list in the source code

**Describe alternatives you've considered**

i couldn't think of any alternatives

**Additional context**

![Screenshot that proves that these emojis are missing](https://user-images.githubusercontent.com/66305550/180637578-25e454e8-9678-4af7-9836-b49948bf2825.png)

**Comment by MajeurAndroid** [comment]
Can you try with the latest release ? You should have them even in 1.4.4b.
Below is 1.4.5.
![Screenshot_2022-08-06-23-25-10-55_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/11336456/183266528-7a2860e1-e7b4-4e5b-ba69-e557b809f739.jpg)

**Comment by Sosasees** [comment]
please reply when version 1.4.5 is on F-Droid so that i can update.
i found and installed OpenBoard on F-Droid

**Comment by Sosasees** [comment]
FDroid notified me of the update.
the update added these missing emojis, thanks. 🙂

**Comment by Sosasees** [comment]
now i noticed that the Die Face emojis ⚀⚁⚂⚃⚄⚅ are missing.
¿should i open a new issue for this?

**Comment by jnnkB** [comment]
Yes, that would be great :)
