### ISSUE TITLE
Emoji Kitchen support

### ISSUE THREAD

**Issue by ThatOneCalculator** [openboard-team/openboard#649]
Adding support for [Emoji Kitchen](https://emoji.supply/kitchen/) emojis from Gboard would be great, there's an [open source version](https://github.com/alcor/emoji-supply) that hopefully shouldn't be too hard to implement.

![image](https://user-images.githubusercontent.com/44733677/180901191-ab4c03ab-a71d-4529-87a5-0c814bfff1ed.png)

**Comment by MajeurAndroid** [comment]
This relies on accessing google servers to get the resulting emoji combination, see https://github.com/alcor/emoji-supply/blob/main/docs/kitchen/script.js#L46. So unfortunately, it is clearly not into a FOSS philosophy :(

**Comment by ThatOneCalculator** [comment]
You could download each combo and self host it
