### ISSUE TITLE
Apk missing from 1.4.5 Release

### ISSUE THREAD

**Issue by Mhowser** [openboard-team/openboard#654]
That is all

**Comment by MajeurAndroid** [comment]
Only @dslul can sign an apk with the keys used in previous releases. I don't have these keys, so the release will be through F-Droid.

**Comment by Mhowser** [comment]
Thanks for letting me know, is it possible to add this information to the release description to avoid further confusion?

**Comment by dslul** [comment]
@Mhowser I uploaded the signed apk both to github and the play store. The latter is under review by Google, sometimes it takes up to a week.

**Comment by Mhowser** [comment]
Thank you!
