### ISSUE TITLE
F-Droid not updated

### ISSUE THREAD

**Issue by ItsRogueRen** [openboard-team/openboard#655]
1.4.5 Release stated F-Droid would be updated a frw hours from release. It's been roughly 24 hours since and F-Droid still hasn't updated with the new version, which lacks an APK to manually install from GitHub

**Comment by MajeurAndroid** [comment]
F-droid bot did noticed the update, see https://gitlab.com/fdroid/fdroiddata/-/commit/69c13964274bca34b2996db24afa72bbe63a7f06.
So we'll juste have to be a bit more patient.
