### ISSUE TITLE
1.4.5 still not on F-droid

### ISSUE THREAD

**Issue by ThatOneCalculator** [openboard-team/openboard#656]
Is something wrong with the build? It still seems to not be on F-droid.

**Comment by MajeurAndroid** [comment]
It is coming, we got our build done, and are now waiting for deployment, see https://monitor.f-droid.org/builds/running.

**Comment by MajeurAndroid** [comment]
It's available.
@chromer030 @Kydaix @yUg-enthusiastic @2Lias @Pentaphon @AlfredEVOL @Finalboss77 @ThatOneCalculator @a4k0san @GoRaN909 @alekksander @Anonymous2716 @akubala @ThatOneCalculator @abhith @citizenserious @NTBBloodbath @MF-Debug @Mhowser @nclettiere @a4k0san
