### ISSUE TITLE
1.4.5 pre-selects wrong character below "s" for German layout

### ISSUE THREAD

**Issue by l3u** [openboard-team/openboard#657]
The new version 1.4.5 introduces a bug using the German layout:

Until now, when long-pressing "s", the "ß" character was pre-selected (as one would expect it and as it should be).

With 1.4.5, "#" is pre-selected when long-pressing "s" instead, and one has to navigate to get a "ß".

**Comment by MajeurAndroid** [comment]
Woops, sorry it must had came back with the new tooling addition, or been missed here https://github.com/openboard-team/openboard/commit/cae0b9e4bc1bcb430f6b764f7b1c50ba0f84f631
I'll fix this soon.

**Comment by l3u** [comment]
Thanks for the quick reply, and of course for fixing it :-)

**Comment by ristein** [comment]
quite annoying, can we expect an update soon?
Last time between updates on F-Droid were 7 months, I would rather downgrade than wait that long

**Comment by UserX404** [comment]
Please create a new version!
The ß-issue is really annoying.

**Comment by Ra72xx** [comment]
*push*
Any update available? This seemingly small inconvenience is extremely annoying when writing in German, and it also seems very easy to fix, so I wonder why the issue is stagnant for over half a year now.

**Comment by l3u** [comment]
I think this has been fixed quite some time ago, we only still lack a new release …
