### ISSUE TITLE
when will dslul will post this app in playstore

### ISSUE THREAD

**Issue by holequantum** [openboard-team/openboard#665]
why it is still not available in playstore when will we have this in playstore what is going wrong does dslul should put have any one contact that person about it or what is wrong

**Comment by MajeurAndroid** [comment]
See /README.md.

**Comment by dslul** [comment]
@holequantum I'm uploading the release right now

**Comment by holequantum** [comment]
thank you so much @dslul. and @MajeurAndroid i install apps from fdroid but i recommend others non tech savvy users to use apps from playstore just because playstore have a lower level system access and can update apps automatically because most users don't update there apps and they stay vulnerable.

**Comment by holequantum** [comment]
> @holequantum I'm uploading the release right now

still update does not arrived yet.

**Comment by dslul** [comment]
> > @holequantum I'm uploading the release right now
> 
> still update does not arrived yet.

that's because Google takes a lot of time to review a release when you haven't published for a while (up to a week)

**Comment by holequantum** [comment]
ohhh i see i did not know about that thanks.

**Comment by holequantum** [comment]
what is the status.?

**Comment by dslul** [comment]
> what is the status.? still update have not arrived.

the update was rejected because of the privacy policy...

**Comment by holequantum** [comment]
> the update was rejected because of the privacy policy...

why what privacy policy. most vulgar apps are in playstore so what is the problem in playstore when it come to the opensource apps
can you elaborate?

**Comment by Pentaphon** [comment]
> the update was rejected because of the privacy policy...

This is a story you can give to the media to help push this along. It wouldn't look good for Google to reject open source keyboards for "privacy" issues.
