### ISSUE TITLE
Cross language suggestions

### ISSUE THREAD

**Issue by yaoberh** [openboard-team/openboard#675]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Sometimes one needs to type in two languages when writing in a messaging app or facebook/twitter/etc, and the dictionary suggestions are always only for the currently in use language/keyboard

**Describe alternatives you've considered**
Google input offers this option as cross language typing/dictionaries

**Comment by NoahAndrews** [comment]
There's actually a draft pull request for this feature: https://github.com/openboard-team/openboard/pull/586

**Comment by jnnkB** [comment]
duplicate of #167 and/or #7
