### ISSUE TITLE
Suggestion menu can't be hidden.

### ISSUE THREAD

**Issue by Cuddle0456** [openboard-team/openboard#682]
**Describe the bug*
Can not turn off suggestion menu.

**To Reproduce**

Turn off everything related suggestions, correction etc.

**Expected behavior**
Suggestion menu shouldn't appear.

**Screenshots**
![185740145-eabdae95-39bd-46e8-b192-30be1fd97644](https://user-images.githubusercontent.com/108587502/185745016-ff35f599-cda5-490a-8b9f-0093efffae21.png)

**Smartphone (please complete the following information):**
 - Device: Samsung A52s
 - OS: Android 12

**Additional context**
On my old android 8 phone, you could turn off this menu after turning off everyrhing related suggestions but it doesn't work on my phone.

**Comment by Helium314** [comment]
Did you have the clipboard key enabled on your old phone?

**Comment by Cuddle0456** [comment]
> Did you have the clipboard key enabled on your old phone?

That fixed it... Thank you I feel so stupid rgiht now, I have no idea how did I miss something like that.
