### ISSUE TITLE
Configurable auto complete aggressiveness

### ISSUE THREAD

**Issue by Pkshields** [openboard-team/openboard#687]
With OpenBoard (and some other Android keyboards), when there is a typo I look at the auto correct row and I can see the correct work I am trying to type, however it isn't bolded so it doesn't get auto completed when I hit space. This leads to me needing to slow my typing, watching the auto correct row, inherently trusting the keyboard less.

It would be useful if I could configure the auto correct to be more aggressive with these auto completes. I'm assuming the keyboard is coming up with a confidence level with each possible correction it is coming up with. If I had a slider I could tweak with to allow auto completes at lower confidence levels, that would sound ideal to me.

**Comment by Helium314** [comment]
If your'e willing to compile the app yourself and play around a bit: I strongly suspect the thing to tweak is `mAutoCorrectionThreshold` in `Suggest.java`, which is set using `readAutoCorrectionThreshold` in `SettingsValues.java`.

I did not investiagate any further which values should do what, but you can find used values in `config-auto-correction-thresholds.xml` (acutally the only used values seem to be `modest` and `off`).

**Comment by Pkshields** [comment]
You're 100% correct in your suspicion, `mAutoCorrectionThreshold` is the key to my needs. Interestingly, if I simply set that to `0` OpenBoard is working exactly as I would like it to - it is autocorrecting everything I type that isn't already a valid word, and it is correctly autocorrecting the word 95% of the time, giving me the confidence I am looking for as I type.

Happy to keep looking into this, with the aim to submit a PR to solve this request. Adding a setting utilising the values you have pointed out in `config-auto-correction-thresholds.xml` could be a nice way to go.

**Comment by Helium314** [comment]
> Happy to keep looking into this, with the aim to submit a PR to solve this request. Adding a setting utilising the values you have pointed out in config-auto-correction-thresholds.xml could be a nice way to go.

I guess an additional setting with a slider or a few selected values would make sense...
