### ISSUE TITLE
missing Die Face emojis

### ISSUE THREAD

**Issue by Sosasees** [openboard-team/openboard#707]
**Is your feature request related to a problem? Please describe.**

after fixing issue https://github.com/openboard-team/openboard/issues/648, i noticed these emoji are missing from OpenBoard's emojis list:
⚀⚁⚂⚃⚄⚅
[(comment)](https://github.com/openboard-team/openboard/issues/648#issuecomment-1219024968)

**Describe the solution you'd like**

please add these emoji to the emojis list. "Symbols" would be the most fitting category.

**Describe alternatives you've considered**

i couldn't think of any alternatives.

**Additional context**

i wanted to take a screenshot of these emojis on the system keyboard, but then i found that system keyboard is also missing them.

since these are real emoji that Unicode has, i think they're a good addition to OpenBoard.

**Comment by harmony5** [comment]
The dice symbols are part of unicode, but aren't actually emojis. There's a dice emoji, though, 🎲, at codepoint `U+1F3B2`. The dices you mentioned start at codepoint `U+2680` (for ⚀), through codepoint `U+2685` (for ⚅).

**Comment by Sosasees** [comment]
> The dice symbols are part of unicode, but aren't actually emojis

then why do they look like emojis?

![screenshot of the die face emojis](https://user-images.githubusercontent.com/66305550/192152125-7ce5b1fa-b6a4-4de7-8a1a-c8a38c544206.png)

**Comment by harmony5** [comment]
> > The dice symbols are part of unicode, but aren't actually emojis
> 
> then why do they look like emojis?
> 
> ![screenshot of the die face emojis](https://user-images.githubusercontent.com/66305550/192152125-7ce5b1fa-b6a4-4de7-8a1a-c8a38c544206.png)

That's only on Samsung phones.

**Comment by harmony5** [comment]
For a full list of official emojis, see: https://www.unicode.org/Public/emoji/14.0/emoji-test.txt

To learn more about what's considered an emoji, see here:
- https://unicode.org/reports/tr51/#Definitions
- https://unicode.org/reports/tr51/#Identification

**Comment by Sosasees** [comment]
> > > The dice symbols are part of unicode, but aren't actually emojis
> > 
> > 
> > then why do they look like emojis?
> > ![screenshot of the die face emojis](https://user-images.githubusercontent.com/66305550/192152125-7ce5b1fa-b6a4-4de7-8a1a-c8a38c544206.png)
> 
> That's only on Samsung phones.

Thanks for this information!

these characters never having been officially made into emoji because they're not important enough is a good reason to close this issue as not planned.
