### ISSUE TITLE
Text prediction not working

### ISSUE THREAD

**Issue by aprunai** [openboard-team/openboard#727]
**Describe the bug**
Though it is enabled in preferences, Openboard is not using previously used word combinations to predict text.

**To Reproduce**
1. Input a sentence, e.g. "The quick brown fox jumps over the lazy dog"; press Enter and repeat some times.
2. Every time, starting with "The" does not suggest the next word in the phrase.

**Expected behavior**
Input of the first word of a previously used sentence should trigger suggestion of the next word in it.

**Smartphone:**
 - Device: Huawei P10 lite
 - OS: Android 9

**Comment by Mrnofish** [comment]
It's working for me in English, after repeating the same sentence twice. Starting from the third 'the' each word is suggested as expected.

**Comment by aprunai** [comment]
I don't know why it isn't working for me. I uninstalled and reinstalled the app, checked permissions, tried repeating phrases again and again. I am attaching a screen of my last attempt - I repeated the same phrase ten times and predictions were still generic.

![IMG_20230124_114424](https://user-images.githubusercontent.com/3056130/214271938-32581571-bc3a-46cb-af1b-6b7df358a4b9.jpg)

**Comment by Mrnofish** [comment]
Make sure that:
- data isn't retained when you uninstall
- the relevant options are enabled in the keyboard settings. OpenBoard > Text Correction > Show Correction Suggestions / Personalised Suggestions / Next word suggestions
- Advanced > Incognito mode is disabled

Done that? Try a few different applications.

If none of the above fixes it, then sorry, I'm out of ideas.

**Comment by aprunai** [comment]
Hello,
I just installed Openboard on another phone (Huawei P30 Lite), with same exact settings, and text prediction is working there.
So I am closing the issue, since it is clearly the handheld's fault.
