### ISSUE TITLE
Could not select the layout "French (AZERTY)"

### ISSUE THREAD

**Issue by rom1v** [openboard-team/openboard#735]
**Describe the bug**
It is impossible to select a French (AZERTY). Other layouts are possible.

**To Reproduce**
Steps to reproduce the behavior (see the video):
 - Go to "Apparence et dispositions" (Appearence and layouts) in preferences
 - In "Divers" (miscellaneous), click on "Styles saisie perso" (Custom layouts)
 - Replace an existing item or add an existing one to French (AZERTY)
 - It fails and a toast is shown with "the selected layout already exists: French (AZERTY)" (this is not the case)

**Expected behavior**
Selecting the layout French (AZERTY) should change the layout to French (AZERTY).

**Video**

https://user-images.githubusercontent.com/543275/204923847-4e1f30b5-adfb-490a-949e-d47d5d9c6415.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A8
 - OS: Android 11
 - OpenBoard 1.4.5 from F-Droid

**Comment by jnnkB** [comment]
Hey @rom1v, I don't think this is a bug, but the toast is actually right. There is no custom French – AZERTY layout but the default French layout (which can be found in the language section) already uses that layout.

**Comment by jnnkB** [comment]
If that's not what you want feel free to reopen this issue :)
